[package]
name = "todo"
version = "1.0.0"
authors = []

[addresses]
todo_addr='0x91ac8ddb4b1a7b91c40577f24d295bbf292d7aa31d0aa52d10148f8822de57e9'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
