[package]
name = "todo"
version = "1.0.0"
authors = []

[addresses]
todo_addr='0x50549aa04f9c027a17913fba29d2cc737926c1ba1ddd6e15310b5b7089ce999b'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
