[package]
name = "todo"
version = "1.0.0"
authors = []

[addresses]
todo_addr='0x949d60b0604cbb3f4b0dfe5a4ba38604e07028224d24f476222fd927660bdcd0'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
