[package]
name = "todo"
version = "1.0.0"
authors = []

[addresses]
todo_addr='0x482ec3f1fcffed38719408d2f394bb211ed6510755efd02d274e0cdcd21ba82b'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
